name: observable
version: 0.24.0
description: Support for marking objects as observable
homepage: https://github.com/google/observable
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.11.0
  dart_internal: ^0.2.1
  meta: ^1.3.0
  quiver: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.2
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
  pedantic: ^1.10.0
  test: ^1.16.8
